class EventData {

  static List<String> cities = [
    'Aberdeen',
    'Armagh',
    'Bath',
    'Belfast',
    'Birmingham',
    'Bolton',
    'Bradford',
    'Bristol',
    'Cambridge',
    'Canterbury',
    'Cardiff',
    'Carlisle',
    'Chichester',
    'Chester',
    'Coventry',
    'Derby',
    'Derry',
    'Doncaster',
    'Dundee',
    'Durham',
    'Ely',
    'Edinburgh',
    'Exeter',
    'Fife',
    'Glasgow',
    'Gloucester',
    'Hereford',
    'Hull',
    'Inverness',
    'Kirklees',
    'Lancaster',
    'Leeds',
    'Leicester',
    'Lichfield',
    'Lincoln',
    'Lisburn',
    'Liverpool',
    'Londonderry',
    'London',
    'Manchester',
    'Newcastle upon Tyne',
    'Newport',
    'Newry',
    'Norwich',
    'North Lanarkshire',
    'Oxford',
    'Peterborough',
    'Plymouth',
    'Portsmouth',
    'Preston',
    'Ripon',
    'Rotherham',
    'Salisbury',
    'Salford',
    'Sandwell',
    'Sefton',
    'Sheffield',
    'Southampton',
    'South Lanarkshire',
    'Stoke-on-Trent',
    'Stockport',
    'Sunderland',
    'Swansea',
    'St Albans',
    'St Davids',
    'Stirling',
    'Truro',
    'Wakefield',
    'Walsall',
    'Wells',
    'Westminster',
    'Wigan',
    'Winchester',
    'Wirral',
    'Wolverhampton',
    'Worcester',
    'York'
  ];

  static List<String> danceGenre = [
    "Konpa",
    "Zouk",
    "Kizomba",
    "Salsa",
    "Semba",
    "Zouk",
    "Kompa",
    "Konpa",
    "Compas",
    "Afro vibes",
    "Afro beats",
    "Afro house",
    "Tarraxinha",
    "Bachata",
    "Tarraxo",
    "Tarraxa",
    "Ghetto Zouk",
    "Urban Kiz",
    "Amapiano",
  ];

  static List<String> eventCategories = [
    "Social",
    "Class",
    "Course",
    "Festival",
    "Workshop"
  ];
}